# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fad12be3ea6ad88bf8516ebc3d136506bb80f328e7b1dbd517e17f0e3445d0c105abb28a37b6835196db43dc01c625266ac0de885826dc47afeeeeaa011364a

test:
  secret_key_base: 98ea06e26aec11e93020eb397ff5f30f2c03d41762a54ea27bb8e27f270bad345927dde2bfa7d9de840ee23a432b696228435306a5e9d152840048a1cd51e5b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
